port: "8000"
mongo:
  im:
    url: "mongodb://localhost:27017"
    database: "im"
    pool_limit: 200
mysql:
  im:
    url: "root:root123456@/im"
    database: "im"
    pool_limit: 200
    max_life_time: 10
    log_mode: true
