// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-08-09 05:46:57.473416 +0700 +07 m=+0.022150180

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/identity/v1/user": {
            "post": {
                "description": "Author: LichTV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Add a new user",
                "parameters": [
                    {
                        "enum": [
                            "en",
                            "vi"
                        ],
                        "type": "string",
                        "description": "string",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "description": "Add a new user body",
                        "name": "UserAddDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    }
                }
            }
        },
        "/identity/v1/user/{user_id}": {
            "get": {
                "description": "Author: LichTV",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "identity"
                ],
                "summary": "Detail info of user",
                "parameters": [
                    {
                        "enum": [
                            "en",
                            "vi"
                        ],
                        "type": "string",
                        "description": "string",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.UserAdd": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@imgo.com"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 3,
                    "example": "Lich Truong"
                },
                "password": {
                    "type": "string",
                    "example": "W3^\u0026(80)\u0026\u0026^x"
                },
                "username": {
                    "type": "string",
                    "format": "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$",
                    "example": "lichtv"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "1991-02-13 10:10:10"
                },
                "email": {
                    "type": "string",
                    "example": "example@imgo.com"
                },
                "full_name": {
                    "type": "string",
                    "example": "Lich Truong"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "modified_at": {
                    "type": "string",
                    "example": "2020-07-15 10:10:10"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "lichtv"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
